# Generated by Django 4.1.6 on 2023-10-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name': 'Event status', 'verbose_name_plural': 'Event status'},
        ),
    ]
